[package]
name = "yapi"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.35", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
egui = "0.35"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json", "rustls", "http2", "charset", "system-proxy", "gzip", "brotli", "deflate", "multipart", "cookies"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
rfd = "0.15"
directories = "5"
sha2 = "0.10"
hmac = "0.12"
rand = "0.8"
regex = "1"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "bmp", "webp", "ico"] }

[profile.release]
opt-level = 2
